spring.datasource:
  type: com.zaxxer.hikari.HikariDataSource
  url: jdbc:h2:mem:pocketdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
  username: sa
  password:
  hikari:
    minimum-idle: 1
    maximum-pool-size: 4
    pool-name: def-pool

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update
  defer-datasource-initialization: true
  open-in-view: false
  database-platform: org.hibernate.dialect.H2Dialect
  properties:
    #jakarta.persistence.query.timeout: 700
    jakarta.persistence.sharedCache.mode: ENABLE_SELECTIVE
    jakarta.persistence.lock.timeout: 700
    hibernate:
      generate_statistics: true
      #format_sql: true

spring.messages:
  basename: messages,spring-jpa-admin-messages,org/hibernate/validator/ValidationMessages

logging.level.org.hibernate.tool.hbm2ddl: DEBUG
logging.level.com.pocketcombats.admin: TRACE
